
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://prism_user:prism_pass@db:5432/prism_db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: prism_user
      POSTGRES_PASSWORD: prism_pass
      POSTGRES_DB: prism_db
    ports:
      - "5432:5432"
